---

- name: Network backup
  hosts: ind11a01.net.racqgroup.local
  gather_facts: false
  connection: network_cli

  vars:
    source_int: loopback0 

  tasks:
    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          ***********************************************************************
          * Access to this computer system is limited to authorised users only. *
          * Unauthorised users may be subject to prosecution under the Crimes   *
          *                        Act or State legislation                     *
          *                                                                     *
          * WARNING: It is a criminal offence to:                               *
          *          i.  Obtain access to data without authority                *
          *          ii. Damage, delete, alter or insert data without authority *
          ***********************************************************************
        state: present
    
    - name: SNMP
      ios_config:
        lines:
         - 10 permit x.x.x.x
        parents: ip access-list standard acl_SNMP
        before: no ip access-list standard acl_SNMP
        match: exact

    - name: NTP_acl
      ios_config:
        lines:
         - 10 permit ip host 10.51.0.1 any
         - 20 permit ip host 10.51.0.2 any
         - 30 permit ip host 10.51.0.3 any
         - 40 permit ip host 10.51.0.4 any
        parents: ip access-list extended acl_NTP
        before: no ip access-list extended acl_NTP
        match: exact

    - name: acl_VTY
      ios_config:
        lines:
         - 10 permit ip x.x.x.x 0.0.0.255 any
         - 20 permit ip x.x.x.x 0.0.0.255 any
        parents: ip access-list extended acl_VTY
        before: no ip access-list extended acl_VTY
        match: exact
    

    - name: Override commands with provided configuration
      cisco.ios.ios_ntp_global:
          config:
            servers:
              - server: 10.51.0.1
              - server: 10.51.0.2
              - server: 10.51.0.3
              - server: 10.51.0.4
            access_group:
                peer:
                - access_list: acl_NTP
            source: "{{ source_int }}"
          state: overridden



    - name: Logging
      cisco.ios.ios_logging_global:
        config:
          buffered:
            severity: informational
            size: 128000
          facility: local6
          hosts:
            - hostname: 10.53.102.45
            - hostname: 10.53.105.17
            - hostname: 10.53.105.40
            - hostname: 10.53.105.32
          source_interface:
            - interface: "{{ source_int }}"
        state: replaced

    - name: AAA config
      ios_config:
        lines:
         - aaa authentication login default group ISETACACS local
         - aaa authentication enable default enable
         - aaa authorization exec default group ISETACACS if-authenticated
         - aaa authorization commands 15 default group ISETACACS local if-authenticated
         - aaa authorization console
         - aaa new-model
         - aaa session-id common
         - ip radius source-interface {{ source_int }}
         - ip tacacs source-interface {{ source_int }}
  
    - name: tacacs servers
      cisco.ios.ios_config:
        lines:
          - address ipv4 10.58.3.31
          -  key 7 xxx
        parents: tacacs server <host>

    - name:  tacacs servers
      cisco.ios.ios_config:
        lines:
          - address ipv4 10.58.4.31
          - key 7 xxx
        parents: tacacs server <host>

    - name:  tacacs servers
      cisco.ios.ios_config:
        lines:
          - address ipv4 10.58.3.30
          - key 7 xxx
        parents: tacacs server <host>

    - name:  tacacs servers
      cisco.ios.ios_config:
        lines:
          - address ipv4 10.58.4.30
          - key 7 xxx
        parents: tacacs server <host>        

    - name: tacacs group
      cisco.ios.ios_config:
        lines:
          - server name <host>
          - server name <host>        
          - server name <host>
          - server name <host>
        parents: aaa group server tacacs+ ISETACACS
...
